### PR TITLE
Update recipe for Crashpad 311a5a2 (24.03.2020)

### PR DESCRIPTION
**Pull request by reneme**
... as included in Chromium 83.

This supersedes [this previous pull request](https://github.com/bincrafters/conan-crashpad/pull/9).

Note that the `extra_cflags_c`-like variables were introduced into the `mini_chromium` build system recently.

### CODE REVIEW

**Comment by reneme** [comment]
The CI on macOS (Travis) and Windows (AppVeyor) works fine now. 👍 
As far as I can see, the GHA builds all fail because some `depot_tools` tool [tries to find a python 2.7 interpreter](https://chromium.googlesource.com/infra/luci/luci-go/+/master/vpython/python/find.go#61) without success:

```
________ running 'download_from_google_storage --no_resume --no_auth --bucket=chromium-clang-format --sha1_file buildtools/linux64/clang-format.sha1' in '/home/conan/.conan/data/crashpad/20200324/bincrafters/testing/source'
Failed to fetch file gs://chromium-clang-format/942fc8b1789144b8071d3fc03ff0fcbe1cf81ac8 for buildtools/linux64/clang-format. [Err: [E2020-05-25T10:49:02.615414Z 689 0 annotate.go:241] goroutine 1:
[E2020-05-25T10:49:02.615507Z 689 0 annotate.go:241] #0 go.chromium.org/luci/vpython/python/find.go:93 - python.Find()
[E2020-05-25T10:49:02.615518Z 689 0 annotate.go:241]   annotation #0:
[E2020-05-25T10:49:02.615526Z 689 0 annotate.go:241]     reason: no Python found
[E2020-05-25T10:49:02.615533Z 689 0 annotate.go:241]   annotation #1:
[E2020-05-25T10:49:02.615540Z 689 0 annotate.go:241]     reason: could not find appropriate executable for: "python2.7"
[E2020-05-25T10:49:02.615548Z 689 0 annotate.go:241]   annotation #2:
[E2020-05-25T10:49:02.615554Z 689 0 annotate.go:241]     reason: could not find target in system
[E2020-05-25T10:49:02.615561Z 689 0 annotate.go:241]     internal reason: target(python2.7)/dirs([/home/conan/.conan/data/depot_tools_installer/20200515/bincrafters/stable/package/be241241e9d4718e5bab4eb33935bbb69606bb0c/bin /home/conan/.conan/data/ninja/1.9.0/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin /home/conan/.conan/data/depot_tools_installer/20200515/bincrafters/stable/package/be241241e9d4718e5bab4eb33935bbb69606bb0c/bin /home/conan/.conan/data/ninja/1.9.0/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin /opt/pyenv/versions/3.7.5/bin /opt/pyenv/libexec /opt/pyenv/plugins/python-build/bin /opt/pyenv/plugins/pyenv-virtualenv/bin /opt/pyenv/plugins/pyenv-update/bin /opt/pyenv/plugins/pyenv-installer/bin /opt/pyenv/plugins/pyenv-doctor/bin /opt/pyenv/shims /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /home/conan/.conan/data/depot_tools_installer/20200515/bincrafters/stable/package/be241241e9d4718e5bab4eb33935bbb69606bb0c/bin])
```

@Croydon Is there a way to bring in a python2.7 interpreter into the GHA CI?

**Comment by Croydon** [comment]
Not without custom engineering for a single recipe. I'm not willing to maintain something like this, sorry

Do you use this recipe on Linux personally?

**Comment by reneme** [comment]
> Not without custom engineering for a single recipe. I'm not willing to maintain something like this, sorry

I get that and its absolutely reasonable.

> Do you use this recipe on Linux personally?

We don't. At least not for the time being. To the best of my knowledge crashpad's support for Linux is also somewhat "limited". I personally never really tried it though.

From my side, just dropping the Linux CI build is totally reasonable. I suppose I'd just drop the `.github` folder from the repo, to do that?

**Comment by Croydon** [comment]
No, please leave all CI scripts untounched, it is better to have it visible that something is not working

Python 2-only compatibility is really painful at this point and will only get worse, so I really hope that all projects migrate quickly

Anyway, if this PR is finished from your perspective I'm willing to accept this PR as it is

**Comment by reneme** [comment]
Yep, done from my point of view.

**Pull request merged**
