### PR TITLE
Update recipe for Crashpad 4367e9d (11.01.2020)

### PR DESCRIPTION
**Pull request by reneme**
... as included in chromium 81...

### CODE REVIEW

**Comment by Croydon** [comment]
Does CI fail because of Python 3?

**Comment by reneme** [comment]
Yes, unfortunately. Locally, I forced the system python version down to 2.7 and it works fine. For the CI I didn't look into it, yet. I was hoping that the Google's build scripts will soon support it...

**Comment by reneme** [comment]
Mhh, [this](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/17aaea21d40dc178638a5e295541fbd8757811c1) and [this](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/c621315d173a9832fc7dcbf3854fe53cdfc5ee6c) commit sound promising.

I.e. newer depot_tools seem to use python 3 by default. Maybe its worth another try.
Edit: Turns out, [it is](https://github.com/bincrafters/community/issues/943#issuecomment-629307967).

**Comment by reneme** [comment]
Closing in favour of https://github.com/bincrafters/conan-crashpad/pull/10.

**Pull request closed without merging**
